[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["npm install", "pip install -r requirements.txt"]

[phases.build]
cmds = ["npm run build"]

[start]
<<<<<<< HEAD
cmd = "npm run start"
=======
cmd = "npm run start"
>>>>>>> b641e086b05dd9f877da67a0b9c1e6b34cfc1040
